"""Generate a self-contained Kaggle notebook (.ipynb) + kernel-metadata.json for one queue run.

The notebook unpacks the tlab-mi-payload dataset, optionally rebuilds the heavy activation dump,
then works through a queue of "<driver>:<stage>" items, each run as
`python scripts/run_<driver>.py --stages <stage>` from the repo root. One driver name is special:
"smoke" runs `scripts/smoke_check.py` directly (no --stages), for the infrastructure smoke test.

    python make_kernel.py --name tlab-mi-smoke --queue smoke --out build/smoke
    python make_kernel.py --name tlab-mi-run1 --queue kernel1_queue.txt --skip-data-restore --out build/run1
    python make_kernel.py --name tlab-mi-run2 --queue kernel2_queue.txt --out build/run2

--queue accepts either a literal comma list ("expA:anatomy,expA:sweep") or a path to a queue file
holding one such line (e.g. kaggle/kernel1_queue.txt) -- the latter is what kernel1_queue.txt /
kernel2_queue.txt / smoke_queue.txt are for.

Regenerate whenever the queue or the driver scripts change; nothing here is hand-edited on Kaggle.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

HERE = Path(__file__).resolve().parent
USERNAME = os.environ.get("KAGGLE_USERNAME", "mortiferumursus")
DATASET_ID = f"{USERNAME}/tlab-mi-payload"

# Heavy dump: activations.py writes data/acts.f16 (~2.3 GB) and data/toks.i32. Everything left
# under /kaggle/working when the kernel finishes becomes its committed output, so those two files
# must never live there -- repo/data is made a symlink into /kaggle/temp/data instead, which Kaggle
# does not persist. Small data/ artifacts (act_stats.pt, splits*.npz, ...) are still copied into
# /kaggle/working/out/data at the end because they're cheap and useful the next morning.
SMALL_DATA_NAMES = [
    "act_stats.pt", "act_stats.json", "splits.npz", "splits_r3.npz", "prompts.json",
    "sae_feature_stats.pt", "concept_positions.npz", "concept_stats.pt",
]

SESSION_LIMIT_HOURS = 12.0
OVERSIZE_LIMIT_BYTES = 200 * 1024 * 1024

INTRO = r"""# T-Lab mech-interp: {NAME}

Generated by `kaggle/make_kernel.py` -- do not hand-edit; regenerate instead. Enable **GPU** and
**Internet** in the notebook settings before running.

Queue for this run: `{QUEUE_DISPLAY}`
Data restore: {DATA_RESTORE_DISPLAY}

Repo data (`repo/data`) is symlinked to `/kaggle/temp/data` so the multi-GB activation dump never
becomes part of this kernel's committed output; only small artifacts, `results/`, `checkpoints/`
and `configs/` are copied to `/kaggle/working/out` at the end.
"""

PIP_INSTALL = r"""import time

t0 = time.time()
get_ipython().system('pip install -q sae-lens==6.49.1 transformer-lens==3.7.0 transformers==5.15.0 datasets==5.0.1')
print(f"pip install done in {time.time() - t0:.1f}s")
# torch, numpy and pandas are intentionally NOT pinned -- take whatever the Kaggle image ships
# (torch matched to the T4 / sm_75 driver stack; numpy/pandas pinned by the image itself).
"""

SETUP = r"""import os, pathlib, shutil, sys, time

INPUT_ROOT = pathlib.Path("/kaggle/input")
# Resolve the attached payload rather than assuming its mount name: a kernel whose dataset was
# still processing at push time comes up with nothing mounted, and the failure is otherwise a bare
# FileNotFoundError three cells later. Print what is actually there either way.
def _find_payload(root, max_depth=4):
    # Locate the payload by STRUCTURE, not by name. Mount layout is not stable across Kaggle
    # images: the same dataset appears either as /kaggle/input/<slug> or nested as
    # /kaggle/input/datasets/<owner>/<slug>. Matching on the presence of src/ + configs/ works
    # under both layouts and survives a rename.
    if not root.exists():
        return None
    stack = [(root, 0)]
    while stack:
        d, depth = stack.pop(0)
        try:
            kids = sorted(p for p in d.iterdir() if p.is_dir())
        except OSError:
            continue
        names = {p.name for p in kids}
        if {"src", "configs"} <= names:
            return d
        if depth < max_depth:
            stack.extend((p, depth + 1) for p in kids)
    return None


print("mounted under /kaggle/input:", sorted(p.name for p in INPUT_ROOT.iterdir()) if INPUT_ROOT.exists() else "(nothing)")
INPUT = _find_payload(INPUT_ROOT)
if INPUT is None:
    raise SystemExit(
        "no payload found under /kaggle/input: expected a directory holding src/ and configs/. "
        "Attach __DATASET_ID__ to this kernel and re-run."
    )
print("using payload:", INPUT, "->", sorted(p.name for p in INPUT.iterdir()))
WORKING = pathlib.Path("/kaggle/working")
REPO = WORKING / "repo"
OUT = WORKING / "out"
LOGS = OUT / "logs"
TEMP = pathlib.Path("/kaggle/temp")
TEMP_DATA = TEMP / "data"

t0 = time.time()
if REPO.exists():
    shutil.rmtree(REPO)
shutil.copytree(INPUT, REPO)
print(f"copied payload -> {REPO} ({time.time() - t0:.1f}s)")

# Move data/ off /kaggle/working before anything writes into it: repo/data becomes a symlink to
# /kaggle/temp/data (not persisted as kernel output), carrying over whatever small files the
# payload already had there (act_stats.pt, splits*.npz, prompts.json, sae_feature_stats.pt, ...).
TEMP.mkdir(parents=True, exist_ok=True)
TEMP_DATA.mkdir(parents=True, exist_ok=True)
payload_data = REPO / "data"
if payload_data.is_dir() and not payload_data.is_symlink():
    for item in payload_data.iterdir():
        shutil.copy2(item, TEMP_DATA / item.name)
    shutil.rmtree(payload_data)
elif payload_data.exists():
    payload_data.unlink()
payload_data.symlink_to(TEMP_DATA, target_is_directory=True)
print(f"repo/data -> {TEMP_DATA} (symlink)")

for d in ("results", "checkpoints"):
    (REPO / d).mkdir(exist_ok=True)
OUT.mkdir(parents=True, exist_ok=True)
LOGS.mkdir(parents=True, exist_ok=True)
print("setup done:", REPO)
"""

DATA_RESTORE = r"""import subprocess, sys, time

SKIP_DATA_RESTORE = __SKIP_DATA_RESTORE__
SRC_DIR = REPO / "src"
ACTS = REPO / "data" / "acts.f16"

if SKIP_DATA_RESTORE:
    print("data restore skipped for this kernel (--skip-data-restore at generation time)")
elif ACTS.exists():
    print(f"data restore skipped: {ACTS} already present")
else:
    steps = [
        ["activations.py", "verify"],
        ["activations.py", "dump", "--n-tokens", "2000000", "--batch-size", "16"],
        ["sae_stats.py", "--chunk", "2048"],
    ]
    for cmd in steps:
        t0 = time.time()
        print(f"\n===== {' '.join(cmd)} =====", flush=True)
        subprocess.run([sys.executable] + cmd, cwd=str(SRC_DIR), check=True)
        print(f"..done in {(time.time() - t0) / 60:.1f} min", flush=True)
    print("\ndata restore complete")
"""

QUEUE_EXEC = r"""import subprocess, sys, time

QUEUE = __QUEUE_LITERAL__

summary = []
for item in QUEUE:
    driver, _, stage = item.partition(":")
    log_path = LOGS / (item.replace(":", "_") + ".log")
    t0 = time.time()
    status = "unknown"
    try:
        if driver == "smoke":
            script = REPO / "scripts" / "smoke_check.py"
            cmd = [sys.executable, str(script)]
        else:
            script = REPO / "scripts" / f"run_{driver}.py"
            cmd = [sys.executable, str(script), "--stages", stage]
        if not script.exists():
            status = "missing driver"
            log_path.write_text(f"driver script not found: {script}\n")
        else:
            with open(log_path, "w") as lf:
                proc = subprocess.run(cmd, cwd=str(REPO), stdout=lf, stderr=subprocess.STDOUT)
            status = "ok" if proc.returncode == 0 else f"failed (rc={proc.returncode})"
    except Exception as e:  # noqa: BLE001 - one bad queue item must not sink the rest
        status = f"error: {e}"
    elapsed_min = (time.time() - t0) / 60
    summary.append({"item": item, "status": status, "minutes": round(elapsed_min, 2)})
    print(f"{item:30s} {status:20s} {elapsed_min:7.2f} min", flush=True)

print("\nqueue finished")
"""

COLLECT = r"""import json, os, pathlib, shutil, time

t0 = time.time()
for d in ("results", "checkpoints", "configs"):
    src = REPO / d
    dst = OUT / d
    if src.exists():
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)
        print(f"copied {d} -> {dst}")

SMALL_DATA = __SMALL_DATA_LITERAL__
data_out = OUT / "data"
data_out.mkdir(exist_ok=True)
for name in SMALL_DATA:
    src = REPO / "data" / name
    if src.is_file():
        shutil.copy2(src, data_out / name)
        print(f"copied data/{name} -> {data_out / name}")

# Safety net: /kaggle/working becomes the kernel's committed output in full. If the heavy dump (or
# anything else) ended up there despite the data/ symlink, remove it rather than let the commit
# choke on a multi-GB output.
OVERSIZE_LIMIT = __OVERSIZE_LIMIT_BYTES__
big = []
for root, dirs, files in os.walk(WORKING):
    for fn in files:
        p = pathlib.Path(root) / fn
        try:
            size = p.stat().st_size
        except OSError:
            continue
        if size > OVERSIZE_LIMIT:
            big.append((p, size))
for p, size in big:
    print(f"WARNING: removing oversized file from /kaggle/working: {p} ({size / 1e6:.0f} MB)")
    p.unlink()
if not big:
    print(f"size check ok: nothing over {OVERSIZE_LIMIT / 1e6:.0f} MB under {WORKING}")

print("\n=== QUEUE SUMMARY ===")
print(f"{'item':30s} {'status':20s} {'minutes':>8s}")
total_min = 0.0
for row in summary:
    print(f"{row['item']:30s} {row['status']:20s} {row['minutes']:8.2f}")
    total_min += row["minutes"]
total_hours = total_min / 60
print(f"\ntotal queue time: {total_hours:.2f} h (session limit ~__SESSION_LIMIT_HOURS__ h)")
if total_hours > __SESSION_LIMIT_HOURS__:
    print("WARNING: queue time exceeds the session limit -- some items likely did not run tonight")
elif total_hours > __SESSION_LIMIT_HOURS__ - 1:
    print("WARNING: close to the session limit")

(OUT / "QUEUE_SUMMARY.json").write_text(
    json.dumps({"queue": summary, "total_minutes": round(total_min, 2),
                "total_hours": round(total_hours, 2),
                "session_limit_hours": __SESSION_LIMIT_HOURS__}, indent=1)
)
print(f"\ncollection done in {time.time() - t0:.1f}s")
"""


def cell(source: str, kind: str = "code") -> dict:
    lines = source.splitlines(keepends=True)
    if kind == "markdown":
        return {"cell_type": "markdown", "metadata": {}, "source": lines}
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": lines}


def resolve_queue(value: str) -> list[str]:
    p = Path(value)
    if p.is_file():
        text = p.read_text(encoding="utf-8")
        line = next((l.strip() for l in text.splitlines() if l.strip() and not l.strip().startswith("#")), "")
        value = line
    items = [x.strip() for x in value.split(",") if x.strip()]
    if not items:
        raise SystemExit(f"empty queue (from {value!r})")
    return items


def env_cell(env: list[str] | None) -> str:
    """One tiny cell exporting KEY=VALUE overrides (e.g. TLAB_LAYER=10) before any stage runs.

    Subprocesses inherit the notebook's environment, so this is how a driver that reads its
    configuration from the environment (run_layer.py) is parameterised without the queue runner
    having to know any extra flags.
    """
    lines = ["import os"]
    for item in env or []:
        k, _, v = item.partition("=")
        lines.append(f"os.environ[{k!r}] = {v!r}")
    lines.append(f"print('env overrides:', {list(env or [])!r})")
    return chr(10).join(lines) + chr(10)


def build_notebook(name: str, queue: list[str], skip_data_restore: bool, env: list[str] | None = None) -> dict:
    queue_literal = json.dumps(queue)
    intro = (
        INTRO.replace("{NAME}", name)
        .replace("{QUEUE_DISPLAY}", ", ".join(queue))
        .replace("{DATA_RESTORE_DISPLAY}", "SKIPPED (--skip-data-restore)" if skip_data_restore else "enabled")
    )
    data_restore = DATA_RESTORE.replace("__SKIP_DATA_RESTORE__", "True" if skip_data_restore else "False")
    queue_exec = QUEUE_EXEC.replace("__QUEUE_LITERAL__", queue_literal)
    collect = (
        COLLECT.replace("__SMALL_DATA_LITERAL__", json.dumps(SMALL_DATA_NAMES))
        .replace("__OVERSIZE_LIMIT_BYTES__", str(OVERSIZE_LIMIT_BYTES))
        .replace("__SESSION_LIMIT_HOURS__", str(SESSION_LIMIT_HOURS))
    )
    return {
        "cells": [
            cell(intro, "markdown"),
            cell(PIP_INSTALL),
            cell(env_cell(env)),
            cell(SETUP.replace("__DATASET_ID__", DATASET_ID)),
            cell(data_restore),
            cell(queue_exec),
            cell(collect),
        ],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10"},
            "accelerator": "GPU",
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def build_kernel_metadata(name: str) -> dict:
    return {
        "id": f"{USERNAME}/{name}",
        "title": name,
        "code_file": f"{name}.ipynb",
        "language": "python",
        "kernel_type": "notebook",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": True,
        "dataset_sources": [DATASET_ID],
        "competition_sources": [],
        "kernel_sources": [],
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--name", required=True, help="kernel slug, e.g. tlab-mi-smoke")
    ap.add_argument("--queue", required=True,
                    help="comma list of driver:stage items, or a path to a queue file with one such line")
    ap.add_argument("--out", type=Path, required=True, help="directory to write <name>.ipynb + kernel-metadata.json")
    ap.add_argument("--env", action="append", default=[], help="KEY=VALUE exported inside the notebook before any stage (repeatable)")
    ap.add_argument("--skip-data-restore", action="store_true",
                    help="bake the notebook to skip rebuilding data/acts.f16 (use for queues that need no heavy dump)")
    args = ap.parse_args()

    queue = resolve_queue(args.queue)
    nb = build_notebook(args.name, queue, args.skip_data_restore, args.env)
    meta = build_kernel_metadata(args.name)

    args.out.mkdir(parents=True, exist_ok=True)
    nb_path = args.out / f"{args.name}.ipynb"
    meta_path = args.out / "kernel-metadata.json"
    nb_path.write_text(json.dumps(nb, indent=1), encoding="utf-8")
    meta_path.write_text(json.dumps(meta, indent=1), encoding="utf-8")

    print(f"wrote {nb_path} ({nb_path.stat().st_size / 1024:.1f} KB)")
    print(f"wrote {meta_path}")
    print(f"queue ({len(queue)} items): {queue}")
    print(f"skip_data_restore={args.skip_data_restore}")


if __name__ == "__main__":
    main()
