"""Kaggle environment smoke check: fast, no heavy-data stages, ~10-15 minutes total.

Ships inside the payload at repo/scripts/smoke_check.py (copied there by build_payload.py) and is
run by the smoke kernel as the single queue item "smoke:check" (see kaggle/smoke_queue.txt and the
queue executor generated by make_kernel.py). Run directly with:

    python scripts/smoke_check.py

from the repo root inside the kernel. Prints PASS/FAIL per check and exits non-zero if any failed,
so the queue executor can record a "failed" status.

Checks, in order:
  1. import transformer_lens
  2. import sae_lens
  3. load gpt2-small (HookedTransformer) and verify the resid_post[6] == resid_pre[7] hook identity
  4. load the gpt2-small-res-jb SAE at blocks.7.hook_resid_pre
  5. `python activations.py verify` as a subprocess, from src/ -- exercises the actual CLI entry
     point the real data-restore step will use, not just the underlying function
  6. stream one document from OpenWebText via `datasets` -- confirms the kernel has internet access
  7. a short generation from gpt2-small -- confirms the model is actually usable, not just loadable
"""

from __future__ import annotations

import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
SRC = REPO / "src"
sys.path.insert(0, str(SRC))

ACT_SHARD = "hf://datasets/Skylion007/openwebtext/plain_text/train-00000-of-00080.parquet"

results: list[tuple[str, bool, str]] = []


def check(name: str):
    def deco(fn):
        def wrapped(*args, **kwargs):
            t0 = time.time()
            try:
                out = fn(*args, **kwargs)
                dt = time.time() - t0
                print(f"PASS: {name} ({dt:.1f}s)")
                results.append((name, True, ""))
                return out
            except Exception as e:  # noqa: BLE001 - a failing check must not kill the others
                dt = time.time() - t0
                print(f"FAIL: {name} ({dt:.1f}s): {e!r}")
                results.append((name, False, repr(e)))
                return None
        return wrapped
    return deco


@check("import transformer_lens")
def check_import_transformer_lens():
    import transformer_lens  # noqa: F401


@check("import sae_lens")
def check_import_sae_lens():
    import sae_lens  # noqa: F401


@check("load gpt2-small + hook identity")
def check_load_model():
    import torch
    from common import load_model

    model = load_model()
    toks = model.to_tokens(["The Eiffel Tower stands in the heart of the French capital"])
    with torch.no_grad():
        _, cache = model.run_with_cache(
            toks, names_filter=["blocks.6.hook_resid_post", "blocks.7.hook_resid_pre"]
        )
    a, b = cache["blocks.6.hook_resid_post"], cache["blocks.7.hook_resid_pre"]
    assert torch.equal(a, b), "hook identity broken"
    return model


@check("load SAE (gpt2-small-res-jb)")
def check_load_sae():
    from common import load_sae

    return load_sae()


@check("activations.py verify (subprocess)")
def check_activations_verify_subprocess():
    r = subprocess.run(
        [sys.executable, "activations.py", "verify"],
        cwd=str(SRC), capture_output=True, text=True,
    )
    print(r.stdout.strip())
    if r.returncode != 0:
        raise RuntimeError(f"activations.py verify exited {r.returncode}: {r.stderr.strip()[-2000:]}")


@check("internet: stream one OpenWebText doc")
def check_internet_dataset():
    from datasets import load_dataset

    ds = load_dataset("parquet", data_files=ACT_SHARD, split="train", streaming=True)
    doc = next(iter(ds))
    text = doc["text"]
    assert isinstance(text, str) and len(text) > 0
    print(f"  got a document, {len(text)} chars")


@check("short generation")
def check_generation(model):
    if model is None:
        raise RuntimeError("no model available (model load check failed earlier)")
    out = model.generate(
        "The Eiffel Tower stands in", max_new_tokens=5, do_sample=False, verbose=False
    )
    print(f"  generated: {out!r}")


def main() -> int:
    check_import_transformer_lens()
    check_import_sae_lens()
    model = check_load_model()
    check_load_sae()
    check_activations_verify_subprocess()
    check_internet_dataset()
    check_generation(model)

    n_pass = sum(1 for _, ok, _ in results if ok)
    print(f"\n{n_pass}/{len(results)} checks passed")
    for name, ok, err in results:
        if not ok:
            print(f"  FAILED: {name}: {err}")
    return 0 if n_pass == len(results) else 1


if __name__ == "__main__":
    sys.exit(main())
