test:
- index: 3272
  freq: 0.000215608
  mean_act: 8.92245
  n_distinct: 5
  content_mass: 1.0
  dec_norm: 1.00001
  var_along: 15.2934
  kappa_tilt: 1.60726
  top_tokens:
  - _Sean
  - Sean
  - _Trey
  - _Hannity
  - _Kathleen
  - agh
  - _Spicer
  - _pm
  - ————————————————
  - _Nguyen
  - leen
  - _Conor
  - ureen
  - _Ashley
  - _±
  keywords:
  - sean
  - trey
  - hannity
  - kathleen
- index: 16355
  freq: 0.000247355
  mean_act: 6.57489
  n_distinct: 4
  content_mass: 1.0
  dec_norm: 1.00006
  var_along: 10.4114
  kappa_tilt: 1.62318
  top_tokens:
  - free
  - _free
  - Free
  - less
  - _Free
  - proof
  - _FREE
  - FREE
  - efficient
  - _neutral
  - based
  - friendly
  - neutral
  - conscious
  - sensitive
  keywords:
  - free
  - less
- index: 14434
  freq: 0.000408069
  mean_act: 5.69383
  n_distinct: 15
  content_mass: 0.97826
  dec_norm: 1.00009
  var_along: 13.4636
  kappa_tilt: 1.96777
  top_tokens:
  - _flow
  - _flows
  - _flowing
  - _Flow
  - _flowed
  - _stream
  - Flow
  - _trickle
  - _of
  - _influx
  - _funnel
  - _currents
  - flow
  - flows
  - _perme
  keywords:
  - flow
  - flows
  - flowing
  - flowed
  - stream
  - trickle
  - influx
  - funnel
  - currents
  - perme
- index: 8925
  freq: 0.000214947
  mean_act: 5.82093
  n_distinct: 7
  content_mass: 0.965261
  dec_norm: 1.00007
  var_along: 13.8662
  kappa_tilt: 1.77739
  top_tokens:
  - _concluded
  - _conclusion
  - _concludes
  - _concluding
  - _conclude
  - _of
  - _concede
  - _ended
  - _observed
  - ched
  - _determined
  - e
  - _found
  - clude
  - clusive
  keywords:
  - concluded
  - conclusion
  - concludes
  - concluding
  - conclude
  - concede
- index: 23860
  freq: 0.000206349
  mean_act: 4.67211
  n_distinct: 13
  content_mass: 0.972304
  dec_norm: 1.0
  var_along: 23.1745
  kappa_tilt: 2.00988
  top_tokens:
  - _defendants
  - _defendant
  - _accused
  - _plaintiff
  - _suspects
  - _deceased
  - _client
  - _Defendant
  - endants
  - endant
  - ant
  - _clients
  - _protagonist
  - _respondent
  - _bellig
  keywords:
  - defendants
  - defendant
  - accused
  - plaintiff
  - suspects
  - deceased
  - client
  - endants
  - endant
  - ant
  - clients
  - protagonist
- index: 5843
  freq: 0.000871693
  mean_act: 1.94857
  n_distinct: 24
  content_mass: 1.0
  dec_norm: 1.00003
  var_along: 14.3942
  kappa_tilt: 2.16524
  top_tokens:
  - _image
  - _images
  - _photos
  - _video
  - _photo
  - _audio
  - _music
  - _pictures
  - _Image
  - Image
  - _text
  - _Pictures
  - _print
  - _film
  - _picture
  keywords:
  - image
  - images
  - photos
  - video
  - photo
  - audio
  - music
  - pictures
  - text
  - print
  - film
  - picture
  - recording
  - article
  - sound
  - paint
  - scene
  - shot
- index: 13094
  freq: 0.000291005
  mean_act: 8.6144
  n_distinct: 6
  content_mass: 1.0
  dec_norm: 1.00002
  var_along: 21.2744
  kappa_tilt: 1.91999
  top_tokens:
  - _youth
  - _Youth
  - _youths
  - _teens
  - _youthful
  - outh
  - _minors
  - _youngsters
  - _juvenile
  - _grassroots
  - _juveniles
  - _youngster
  - _academy
  - _skate
  - _youngest
  keywords:
  - youth
  - youths
  - teens
  - youthful
  - outh
- index: 7998
  freq: 0.000396825
  mean_act: 8.47157
  n_distinct: 4
  content_mass: 1.0
  dec_norm: 1.00006
  var_along: 13.1291
  kappa_tilt: 1.54563
  top_tokens:
  - _referred
  - _referring
  - _refer
  - _refers
  - Refer
  - ring
  - _reference
  - ferred
  - erred
  - tains
  - _referrals
  - _gest
  - _redirect
  - _linked
  - _dispar
  keywords:
  - referred
  - referring
  - refer
  - refers
- index: 15503
  freq: 0.000482804
  mean_act: 4.63434
  n_distinct: 22
  content_mass: 0.980638
  dec_norm: 1.00007
  var_along: 12.8146
  kappa_tilt: 1.6648
  top_tokens:
  - _wildly
  - _hugely
  - _vastly
  - _hotly
  - _massively
  - _dramatically
  - _sharply
  - _mutually
  - _grossly
  - _bitterly
  - _overly
  - _drastically
  - _instantly
  - _desperately
  - _immensely
  keywords:
  - wildly
  - hugely
  - vastly
  - hotly
  - massively
  - dramatically
  - sharply
  - mutually
  - grossly
  - bitterly
  - overly
  - drastically
  - instantly
  - desperately
  - immensely
  - fiercely
  - radically
  - ridiculously
  - utterly
  - tremendously
  - endlessly
- index: 4151
  freq: 0.000847222
  mean_act: 2.64303
  n_distinct: 18
  content_mass: 1.0
  dec_norm: 1.00004
  var_along: 12.9373
  kappa_tilt: 1.76879
  top_tokens:
  - _committed
  - _determined
  - _convinced
  - _focused
  - _prepared
  - _opposed
  - _engaged
  - _close
  - _dedicated
  - _married
  - _supported
  - _obsessed
  - _ready
  - _devoted
  - _passionate
  keywords:
  - committed
  - determined
  - convinced
  - focused
  - prepared
  - opposed
  - engaged
  - close
  - dedicated
  - married
  - supported
  - obsessed
  - ready
  - devoted
  - passionate
  - motivated
  - divided
  - open
- index: 17590
  freq: 0.00372553
  mean_act: 1.47817
  n_distinct: 7
  content_mass: 0.970728
  dec_norm: 1.00006
  var_along: 12.2122
  kappa_tilt: 1.79726
  top_tokens:
  - _said
  - _told
  - _says
  - _explained
  - _tells
  - _that
  - _revealed
  - _saying
  - _claims
  - _insists
  - _telling
  - _called
  - _expressed
  - _"
  - _he
  keywords:
  - said
  - told
  - says
  - explained
  - tells
  - that
  - revealed
- index: 835
  freq: 0.000312169
  mean_act: 9.13715
  n_distinct: 4
  content_mass: 1.0
  dec_norm: 1.00006
  var_along: 15.568
  kappa_tilt: 1.79017
  top_tokens:
  - _complex
  - _complicated
  - _complexity
  - _elaborate
  - _sophisticated
  - _intricate
  - _Complex
  - complex
  - _delicate
  - _nuanced
  - plex
  - _complexities
  - _of
  - _and
  - _flawed
  keywords:
  - complex
  - complicated
  - complexity
  - elaborate
dev:
- index: 24487
  freq: 0.000408069
  mean_act: 6.48779
  n_distinct: 4
  content_mass: 1.0
  dec_norm: 1.00005
  var_along: 14.9818
  kappa_tilt: 1.92735
  top_tokens:
  - _appearance
  - _appearances
  - _appearing
  - _appear
  - _appeared
  - earance
  - Appearance
  - _of
  - _cameo
  - earances
  - _disappearance
  - _Appearance
  - os
  - _performances
  - Appearances
  keywords:
  - appearance
  - appearances
  - appearing
  - appear
- index: 10388
  freq: 0.00051455
  mean_act: 3.65092
  n_distinct: 22
  content_mass: 0.956035
  dec_norm: 1.00004
  var_along: 19.616
  kappa_tilt: 2.14138
  top_tokens:
  - _Madrid
  - _Milan
  - _Mourinho
  - _Chennai
  - _Munich
  - _Dortmund
  - _Nadu
  - _Monaco
  - _Ramos
  - _Kerala
  - _Lyon
  - _Ll
  - _Carlo
  - iano
  - _Ronaldo
  keywords:
  - madrid
  - milan
  - mourinho
  - chennai
  - munich
  - dortmund
  - nadu
  - monaco
  - ramos
  - kerala
  - lyon
  - carlo
  - iano
  - ronaldo
  - tamil
  - monte
  - trafford
  - inquisitor
  - sev
  - liga
- index: 17242
  freq: 0.00246296
  mean_act: 2.70627
  n_distinct: 7
  content_mass: 0.964812
  dec_norm: 1.0001
  var_along: 15.6942
  kappa_tilt: 1.66119
  top_tokens:
  - _happened
  - _occurred
  - _place
  - _held
  - _came
  - _out
  - _took
  - _made
  - _reported
  - _began
  - _struck
  - _started
  - _unfolded
  - _taken
  - _sparked
  keywords:
  - happened
  - occurred
  - place
  - held
  - came
  - out
  - took
- index: 1171
  freq: 0.000306217
  mean_act: 4.76424
  n_distinct: 11
  content_mass: 0.964135
  dec_norm: 1.00003
  var_along: 16.0401
  kappa_tilt: 1.83039
  top_tokens:
  - _Fame
  - _induct
  - _Hall
  - _induction
  - _fame
  - ed
  - _Academy
  - amer
  - _impeachment
  - _F
  - _Dame
  - ardi
  - _Bowl
  - ighthouse
  - ive
  keywords:
  - fame
  - induct
  - hall
  - induction
  - academy
  - amer
  - impeachment
  - dame
- index: 8475
  freq: 0.000384921
  mean_act: 4.18803
  n_distinct: 18
  content_mass: 1.0
  dec_norm: 1.00008
  var_along: 14.7267
  kappa_tilt: 2.162
  top_tokens:
  - _inspection
  - _inspectors
  - _inspections
  - _inspector
  - _inspect
  - _Inspector
  - _audit
  - _Inspect
  - _inventory
  - _inspected
  - _inspecting
  - _examination
  - _scouting
  - _Inspection
  - pection
  keywords:
  - inspection
  - inspectors
  - inspections
  - inspector
  - inspect
  - audit
  - inventory
  - inspected
  - inspecting
  - examination
  - scouting
  - pection
  - spect
  - tours
  - sted
- index: 21592
  freq: 0.000232804
  mean_act: 10.7192
  n_distinct: 7
  content_mass: 0.973831
  dec_norm: 1.00004
  var_along: 11.2789
  kappa_tilt: 1.38865
  top_tokens:
  - _Comp
  - comp
  - Comp
  - _comp
  - _compost
  - _COMP
  - �
  - omp
  - _compressed
  - _decomp
  - _incomp
  - _compet
  - _compression
  - _uncomp
  - _compat
  keywords:
  - comp
  - compost
test_r3:
- index: 1344
  freq: 0.000285714
  mean_act: 5.08552
  n_distinct: 22
  content_mass: 0.837247
  dec_norm: 1.00005
  var_along: 10.8339
  kappa_tilt: 1.63094
  top_tokens:
  - _Alpha
  - _Delta
  - _alpha
  - _ALP
  - _gamma
  - _Omega
  - _Eagle
  - α
  - _Sigma
  - _beta
  - _�
  - _Beta
  - Beta
  - _Telegram
  - eta
  keywords:
  - alpha
  - delta
  - alp
  - gamma
  - omega
  - eagle
  - sigma
  - beta
  - telegram
  - eta
  - vega
  - emperor
  - angels
  - amino
  - kepler
- index: 17102
  freq: 0.000446429
  mean_act: 4.40781
  n_distinct: 15
  content_mass: 1.0
  dec_norm: 1.00003
  var_along: 26.2252
  kappa_tilt: 1.8522
  top_tokens:
  - _mosque
  - _Mosque
  - _church
  - _synagogue
  - _monastery
  - _Cathedral
  - _churches
  - _rink
  - _cathedral
  - abad
  - _mosques
  - _Imam
  - _Koran
  - _lighthouse
  - jiang
  keywords:
  - mosque
  - church
  - synagogue
  - monastery
  - cathedral
  - churches
  - rink
  - abad
  - mosques
  - imam
  - koran
  - lighthouse
  - jiang
- index: 15507
  freq: 0.000195767
  mean_act: 7.45934
  n_distinct: 3
  content_mass: 1.0
  dec_norm: 1.00006
  var_along: 9.95352
  kappa_tilt: 1.54504
  top_tokens:
  - _example
  - _instance
  - _particular
  - ','
  - _say
  - _meanwhile
  - _things
  - _less
  - _matter
  - _hand
  - _others
  - _notably
  - _name
  - _starters
  - _respectively
  keywords:
  - example
  - instance
  - particular
- index: 14891
  freq: 0.000271825
  mean_act: 4.9139
  n_distinct: 13
  content_mass: 0.892093
  dec_norm: 1.00003
  var_along: 13.215
  kappa_tilt: 1.92879
  top_tokens:
  - _bowl
  - _Bowl
  - �
  - owl
  - _soup
  - _||
  - _basket
  - _bowling
  - _Bowling
  - _bowls
  - _pitcher
  - _captain
  - _blender
  - _Pavilion
  - _basin
  keywords:
  - bowl
  - owl
  - soup
  - basket
  - bowling
  - bowls
  - pitcher
  - captain
  - blender
- index: 4317
  freq: 0.000300265
  mean_act: 5.32181
  n_distinct: 14
  content_mass: 1.0
  dec_norm: 1.00001
  var_along: 14.9322
  kappa_tilt: 2.12221
  top_tokens:
  - _clash
  - _collision
  - _clashes
  - _collided
  - _clashed
  - _confrontation
  - _collisions
  - _altercation
  - _collide
  - _scrimmage
  - _showdown
  - _conver
  - _brawl
  - ashing
  - _concussion
  keywords:
  - clash
  - collision
  - clashes
  - collided
  - clashed
  - confrontation
  - collisions
  - altercation
  - collide
  - scrimmage
  - showdown
  - conver
  - brawl
  - ashing
- index: 23257
  freq: 0.000191799
  mean_act: 10.1356
  n_distinct: 4
  content_mass: 1.0
  dec_norm: 1.00002
  var_along: 11.7385
  kappa_tilt: 1.79506
  top_tokens:
  - _string
  - _strings
  - String
  - _String
  - string
  - _dwarf
  - strings
  - _unspecified
  - ING
  - _Brass
  - ring
  - _spree
  - _hamstring
  - _Thames
  - _constellation
  keywords:
  - string
  - strings
- index: 15664
  freq: 0.000396164
  mean_act: 4.59181
  n_distinct: 10
  content_mass: 0.932621
  dec_norm: 1.00006
  var_along: 15.1658
  kappa_tilt: 1.99053
  top_tokens:
  - _Kingdom
  - _kingdom
  - dom
  - _kingdoms
  - _Empire
  - _monarchy
  - _Kushner
  - _Kingdoms
  - _KR
  - King
  - _desp
  - edom
  - _JP
  - _DPRK
  - _throne
  keywords:
  - kingdom
  - dom
  - kingdoms
  - empire
  - monarchy
  - kushner
  - king
- index: 7848
  freq: 0.000132937
  mean_act: 6.22403
  n_distinct: 11
  content_mass: 0.821347
  dec_norm: 1.00004
  var_along: 9.92833
  kappa_tilt: 1.29278
  top_tokens:
  - _besides
  - _Besides
  - Besides
  - _Beyond
  - Aside
  - _Aside
  - _beside
  - Apart
  - _beyond
  - ide
  - esides
  - _Plus
  - _from
  - Beyond
  - _to
  keywords:
  - besides
  - beyond
  - aside
  - beside
  - apart
  - ide
  - esides
- index: 6587
  freq: 0.000289021
  mean_act: 4.36376
  n_distinct: 21
  content_mass: 0.938132
  dec_norm: 1.00003
  var_along: 11.1362
  kappa_tilt: 1.46455
  top_tokens:
  - _lean
  - _leaning
  - Lean
  - _Lean
  - _leaned
  - _slumped
  - er
  - leaning
  - lean
  - _Burke
  - ings
  - _shoulders
  - _tilt
  - _inclined
  - _grav
  keywords:
  - lean
  - leaning
  - leaned
  - slumped
  - burke
  - ings
  - shoulders
  - tilt
  - inclined
  - grav
  - hun
  - skew
  - bang
  - utz
  - kun
  - overly
- index: 359
  freq: 0.000181878
  mean_act: 6.28127
  n_distinct: 4
  content_mass: 0.971595
  dec_norm: 1.00001
  var_along: 26.3662
  kappa_tilt: 1.79972
  top_tokens:
  - _Twitter
  - _Reddit
  - +
  - Twitter
  - _Google
  - _Email
  - _Facebook
  - _email
  - _LinkedIn
  - _Live
  - _tweet
  - _media
  - com
  - _Tumblr
  - _reddit
  keywords:
  - twitter
  - reddit
- index: 6911
  freq: 0.000337963
  mean_act: 4.78736
  n_distinct: 15
  content_mass: 0.975491
  dec_norm: 1.00005
  var_along: 18.3571
  kappa_tilt: 1.8871
  top_tokens:
  - _Flynn
  - _Manafort
  - _Kushner
  - _Yates
  - ahl
  - _Fitzpatrick
  - _LinkedIn
  - _Freeman
  - _Clarke
  - _Cobb
  - _Kell
  - _Conway
  - lynn
  - _Rasmussen
  - opoulos
  keywords:
  - flynn
  - manafort
  - kushner
  - yates
  - ahl
  - fitzpatrick
  - linkedin
  - freeman
  - clarke
  - cobb
  - kell
  - conway
  - lynn
  - rasmussen
  - opoulos
- index: 4398
  freq: 0.000229497
  mean_act: 9.32141
  n_distinct: 3
  content_mass: 1.0
  dec_norm: 1.00003
  var_along: 13.6997
  kappa_tilt: 2.02313
  top_tokens:
  - _battery
  - _batteries
  - _lithium
  - _Lith
  - Battery
  - _garage
  - attery
  - _Baton
  - _warranty
  - _GPU
  - _brightness
  - _Gardner
  - _Buster
  - _Berry
  - '-'
  keywords:
  - battery
  - batteries
  - lithium
