test:
- index: 3272
  freq: 0.000215608
  mean_act: 8.92245
  n_distinct: 5
  content_mass: 1.0
  dec_norm: 1.00001
  var_along: 15.2934
  kappa_tilt: 1.60726
  top_tokens:
  - _Sean
  - Sean
  - _Trey
  - _Hannity
  - _Kathleen
  - agh
  - _Spicer
  - _pm
  - ————————————————
  - _Nguyen
  - leen
  - _Conor
  - ureen
  - _Ashley
  - _±
  keywords:
  - sean
  - trey
  - hannity
  - kathleen
- index: 16355
  freq: 0.000247355
  mean_act: 6.57489
  n_distinct: 4
  content_mass: 1.0
  dec_norm: 1.00006
  var_along: 10.4114
  kappa_tilt: 1.62318
  top_tokens:
  - free
  - _free
  - Free
  - less
  - _Free
  - proof
  - _FREE
  - FREE
  - efficient
  - _neutral
  - based
  - friendly
  - neutral
  - conscious
  - sensitive
  keywords:
  - free
  - less
- index: 14434
  freq: 0.000408069
  mean_act: 5.69383
  n_distinct: 15
  content_mass: 0.97826
  dec_norm: 1.00009
  var_along: 13.4636
  kappa_tilt: 1.96777
  top_tokens:
  - _flow
  - _flows
  - _flowing
  - _Flow
  - _flowed
  - _stream
  - Flow
  - _trickle
  - _of
  - _influx
  - _funnel
  - _currents
  - flow
  - flows
  - _perme
  keywords:
  - flow
  - flows
  - flowing
  - flowed
  - stream
  - trickle
  - influx
  - funnel
  - currents
  - perme
- index: 8925
  freq: 0.000214947
  mean_act: 5.82093
  n_distinct: 7
  content_mass: 0.965261
  dec_norm: 1.00007
  var_along: 13.8662
  kappa_tilt: 1.77739
  top_tokens:
  - _concluded
  - _conclusion
  - _concludes
  - _concluding
  - _conclude
  - _of
  - _concede
  - _ended
  - _observed
  - ched
  - _determined
  - e
  - _found
  - clude
  - clusive
  keywords:
  - concluded
  - conclusion
  - concludes
  - concluding
  - conclude
  - concede
- index: 23860
  freq: 0.000206349
  mean_act: 4.67211
  n_distinct: 13
  content_mass: 0.972304
  dec_norm: 1.0
  var_along: 23.1745
  kappa_tilt: 2.00988
  top_tokens:
  - _defendants
  - _defendant
  - _accused
  - _plaintiff
  - _suspects
  - _deceased
  - _client
  - _Defendant
  - endants
  - endant
  - ant
  - _clients
  - _protagonist
  - _respondent
  - _bellig
  keywords:
  - defendants
  - defendant
  - accused
  - plaintiff
  - suspects
  - deceased
  - client
  - endants
  - endant
  - ant
  - clients
  - protagonist
- index: 5843
  freq: 0.000871693
  mean_act: 1.94857
  n_distinct: 24
  content_mass: 1.0
  dec_norm: 1.00003
  var_along: 14.3942
  kappa_tilt: 2.16524
  top_tokens:
  - _image
  - _images
  - _photos
  - _video
  - _photo
  - _audio
  - _music
  - _pictures
  - _Image
  - Image
  - _text
  - _Pictures
  - _print
  - _film
  - _picture
  keywords:
  - image
  - images
  - photos
  - video
  - photo
  - audio
  - music
  - pictures
  - text
  - print
  - film
  - picture
  - recording
  - article
  - sound
  - paint
  - scene
  - shot
- index: 13094
  freq: 0.000291005
  mean_act: 8.6144
  n_distinct: 6
  content_mass: 1.0
  dec_norm: 1.00002
  var_along: 21.2744
  kappa_tilt: 1.91999
  top_tokens:
  - _youth
  - _Youth
  - _youths
  - _teens
  - _youthful
  - outh
  - _minors
  - _youngsters
  - _juvenile
  - _grassroots
  - _juveniles
  - _youngster
  - _academy
  - _skate
  - _youngest
  keywords:
  - youth
  - youths
  - teens
  - youthful
  - outh
- index: 7998
  freq: 0.000396825
  mean_act: 8.47157
  n_distinct: 4
  content_mass: 1.0
  dec_norm: 1.00006
  var_along: 13.1291
  kappa_tilt: 1.54563
  top_tokens:
  - _referred
  - _referring
  - _refer
  - _refers
  - Refer
  - ring
  - _reference
  - ferred
  - erred
  - tains
  - _referrals
  - _gest
  - _redirect
  - _linked
  - _dispar
  keywords:
  - referred
  - referring
  - refer
  - refers
- index: 15503
  freq: 0.000482804
  mean_act: 4.63434
  n_distinct: 22
  content_mass: 0.980638
  dec_norm: 1.00007
  var_along: 12.8146
  kappa_tilt: 1.6648
  top_tokens:
  - _wildly
  - _hugely
  - _vastly
  - _hotly
  - _massively
  - _dramatically
  - _sharply
  - _mutually
  - _grossly
  - _bitterly
  - _overly
  - _drastically
  - _instantly
  - _desperately
  - _immensely
  keywords:
  - wildly
  - hugely
  - vastly
  - hotly
  - massively
  - dramatically
  - sharply
  - mutually
  - grossly
  - bitterly
  - overly
  - drastically
  - instantly
  - desperately
  - immensely
  - fiercely
  - radically
  - ridiculously
  - utterly
  - tremendously
  - endlessly
- index: 4151
  freq: 0.000847222
  mean_act: 2.64303
  n_distinct: 18
  content_mass: 1.0
  dec_norm: 1.00004
  var_along: 12.9373
  kappa_tilt: 1.76879
  top_tokens:
  - _committed
  - _determined
  - _convinced
  - _focused
  - _prepared
  - _opposed
  - _engaged
  - _close
  - _dedicated
  - _married
  - _supported
  - _obsessed
  - _ready
  - _devoted
  - _passionate
  keywords:
  - committed
  - determined
  - convinced
  - focused
  - prepared
  - opposed
  - engaged
  - close
  - dedicated
  - married
  - supported
  - obsessed
  - ready
  - devoted
  - passionate
  - motivated
  - divided
  - open
- index: 17590
  freq: 0.00372553
  mean_act: 1.47817
  n_distinct: 7
  content_mass: 0.970728
  dec_norm: 1.00006
  var_along: 12.2122
  kappa_tilt: 1.79726
  top_tokens:
  - _said
  - _told
  - _says
  - _explained
  - _tells
  - _that
  - _revealed
  - _saying
  - _claims
  - _insists
  - _telling
  - _called
  - _expressed
  - _"
  - _he
  keywords:
  - said
  - told
  - says
  - explained
  - tells
  - that
  - revealed
- index: 835
  freq: 0.000312169
  mean_act: 9.13715
  n_distinct: 4
  content_mass: 1.0
  dec_norm: 1.00006
  var_along: 15.568
  kappa_tilt: 1.79017
  top_tokens:
  - _complex
  - _complicated
  - _complexity
  - _elaborate
  - _sophisticated
  - _intricate
  - _Complex
  - complex
  - _delicate
  - _nuanced
  - plex
  - _complexities
  - _of
  - _and
  - _flawed
  keywords:
  - complex
  - complicated
  - complexity
  - elaborate
dev:
- index: 24487
  freq: 0.000408069
  mean_act: 6.48779
  n_distinct: 4
  content_mass: 1.0
  dec_norm: 1.00005
  var_along: 14.9818
  kappa_tilt: 1.92735
  top_tokens:
  - _appearance
  - _appearances
  - _appearing
  - _appear
  - _appeared
  - earance
  - Appearance
  - _of
  - _cameo
  - earances
  - _disappearance
  - _Appearance
  - os
  - _performances
  - Appearances
  keywords:
  - appearance
  - appearances
  - appearing
  - appear
- index: 10388
  freq: 0.00051455
  mean_act: 3.65092
  n_distinct: 22
  content_mass: 0.956035
  dec_norm: 1.00004
  var_along: 19.616
  kappa_tilt: 2.14138
  top_tokens:
  - _Madrid
  - _Milan
  - _Mourinho
  - _Chennai
  - _Munich
  - _Dortmund
  - _Nadu
  - _Monaco
  - _Ramos
  - _Kerala
  - _Lyon
  - _Ll
  - _Carlo
  - iano
  - _Ronaldo
  keywords:
  - madrid
  - milan
  - mourinho
  - chennai
  - munich
  - dortmund
  - nadu
  - monaco
  - ramos
  - kerala
  - lyon
  - carlo
  - iano
  - ronaldo
  - tamil
  - monte
  - trafford
  - inquisitor
  - sev
  - liga
- index: 17242
  freq: 0.00246296
  mean_act: 2.70627
  n_distinct: 7
  content_mass: 0.964812
  dec_norm: 1.0001
  var_along: 15.6942
  kappa_tilt: 1.66119
  top_tokens:
  - _happened
  - _occurred
  - _place
  - _held
  - _came
  - _out
  - _took
  - _made
  - _reported
  - _began
  - _struck
  - _started
  - _unfolded
  - _taken
  - _sparked
  keywords:
  - happened
  - occurred
  - place
  - held
  - came
  - out
  - took
- index: 1171
  freq: 0.000306217
  mean_act: 4.76424
  n_distinct: 11
  content_mass: 0.964135
  dec_norm: 1.00003
  var_along: 16.0401
  kappa_tilt: 1.83039
  top_tokens:
  - _Fame
  - _induct
  - _Hall
  - _induction
  - _fame
  - ed
  - _Academy
  - amer
  - _impeachment
  - _F
  - _Dame
  - ardi
  - _Bowl
  - ighthouse
  - ive
  keywords:
  - fame
  - induct
  - hall
  - induction
  - academy
  - amer
  - impeachment
  - dame
- index: 8475
  freq: 0.000384921
  mean_act: 4.18803
  n_distinct: 18
  content_mass: 1.0
  dec_norm: 1.00008
  var_along: 14.7267
  kappa_tilt: 2.162
  top_tokens:
  - _inspection
  - _inspectors
  - _inspections
  - _inspector
  - _inspect
  - _Inspector
  - _audit
  - _Inspect
  - _inventory
  - _inspected
  - _inspecting
  - _examination
  - _scouting
  - _Inspection
  - pection
  keywords:
  - inspection
  - inspectors
  - inspections
  - inspector
  - inspect
  - audit
  - inventory
  - inspected
  - inspecting
  - examination
  - scouting
  - pection
  - spect
  - tours
  - sted
- index: 21592
  freq: 0.000232804
  mean_act: 10.7192
  n_distinct: 7
  content_mass: 0.973831
  dec_norm: 1.00004
  var_along: 11.2789
  kappa_tilt: 1.38865
  top_tokens:
  - _Comp
  - comp
  - Comp
  - _comp
  - _compost
  - _COMP
  - �
  - omp
  - _compressed
  - _decomp
  - _incomp
  - _compet
  - _compression
  - _uncomp
  - _compat
  keywords:
  - comp
  - compost
test_r3:
- index: 18537
  freq: 0.000561508
  mean_act: 8.90631
  n_distinct: 3
  content_mass: 1.0
  dec_norm: 1.00004
  var_along: 11.9983
  kappa_tilt: 1.55928
  top_tokens:
  - _allow
  - _allowing
  - _allowed
  - _allows
  - _Allow
  - owing
  - allow
  - _permit
  - _permitted
  - allows
  - _permitting
  - owed
  - _allowance
  keywords:
  - allow
  - allowing
  - allowed
- index: 16446
  freq: 0.000173942
  mean_act: 8.5508
  n_distinct: 5
  content_mass: 0.977693
  dec_norm: 1.00004
  var_along: 11.7701
  kappa_tilt: 1.70659
  top_tokens:
  - _Christ
  - Christ
  - _CHRIST
  - _Him
  - _christ
  - _Messiah
  - iour
  - christ
  - _euth
  - rament
  - _Ether
  - _é
  - Thom
  - ν
  - _ego
  keywords:
  - christ
  - him
- index: 3758
  freq: 0.000279101
  mean_act: 5.7294
  n_distinct: 13
  content_mass: 0.969649
  dec_norm: 1.00001
  var_along: 17.4079
  kappa_tilt: 1.9316
  top_tokens:
  - _Vatican
  - _Rome
  - _pope
  - atican
  - _Benedict
  - _Cardinals
  - OME
  - _Cardinal
  - _Louisville
  - _Pont
  - ICAN
  - _pont
  - _cardinal
  - _Madonna
  - ical
  keywords:
  - vatican
  - rome
  - pope
  - atican
  - benedict
  - cardinals
  - ome
  - cardinal
  - louisville
  - pont
  - ican
- index: 6046
  freq: 0.000230159
  mean_act: 4.68653
  n_distinct: 18
  content_mass: 0.754854
  dec_norm: 1.00002
  var_along: 21.4178
  kappa_tilt: 1.96816
  top_tokens:
  - _cafe
  - _Cafe
  - _café
  - _Café
  - _Cinema
  - afe
  - _cinema
  - affe
  - _Bak
  - _arcade
  - _cafes
  - _cafeteria
  - _caf
  - _Coffee
  - _meme
  keywords:
  - cafe
  - café
  - cinema
  - afe
  - affe
  - bak
  - arcade
  - cafes
  - cafeteria
  - caf
  - coffee
  - meme
  - plaza
  - zza
  - diner
- index: 14067
  freq: 0.00039881
  mean_act: 4.05653
  n_distinct: 18
  content_mass: 0.987477
  dec_norm: 1.00004
  var_along: 14.4018
  kappa_tilt: 1.87904
  top_tokens:
  - _explosive
  - _explosives
  - _incendiary
  - _fireworks
  - _deton
  - _bombshell
  - _grenade
  - _dynam
  - _bomb
  - _Explosive
  - acker
  - _destructive
  - _Derrick
  - _volatile
  - aston
  keywords:
  - explosive
  - explosives
  - incendiary
  - fireworks
  - deton
  - bombshell
  - grenade
  - dynam
  - bomb
  - acker
  - destructive
  - derrick
  - volatile
  - aston
  - seismic
  - device
  - ive
- index: 4752
  freq: 0.000892857
  mean_act: 3.23505
  n_distinct: 16
  content_mass: 0.93799
  dec_norm: 1.00005
  var_along: 16.9289
  kappa_tilt: 2.17319
  top_tokens:
  - _watch
  - _view
  - _play
  - _share
  - _receive
  - _see
  - _continue
  - _read
  - _help
  - _download
  - _email
  - _enlarge
  - _register
  - _send
  - _original
  keywords:
  - watch
  - view
  - play
  - share
  - receive
  - see
  - continue
  - read
  - help
  - download
  - email
  - enlarge
  - register
  - send
  - original
  - update
- index: 12625
  freq: 0.000343254
  mean_act: 16.0536
  n_distinct: 3
  content_mass: 1.0
  dec_norm: 1.00005
  var_along: 12.1304
  kappa_tilt: 1.48604
  top_tokens:
  - _feel
  - _felt
  - _feeling
  - _feels
  - _Feel
  - feel
  - felt
  - Feel
  - _Feeling
  - elt
  keywords:
  - feel
  - felt
  - feeling
- index: 13178
  freq: 0.000316799
  mean_act: 3.91162
  n_distinct: 15
  content_mass: 1.0
  dec_norm: 1.00004
  var_along: 10.7631
  kappa_tilt: 1.7011
  top_tokens:
  - _Love
  - Love
  - _love
  - _LOVE
  - _Lucy
  - love
  - _Valentine
  - _Pride
  - _Hate
  - _Life
  - _Friendship
  - _Paradise
  - _Like
  - _Leslie
  - oving
  keywords:
  - love
  - lucy
  - valentine
  - pride
  - hate
  - life
  - friendship
  - paradise
  - like
  - leslie
  - oving
- index: 18931
  freq: 0.000291667
  mean_act: 3.81268
  n_distinct: 20
  content_mass: 0.930921
  dec_norm: 1.0
  var_along: 10.373
  kappa_tilt: 1.58999
  top_tokens:
  - _wound
  - _wounds
  - _winding
  - _wounded
  - _Wen
  - _burns
  - _trauma
  - _Heb
  - _scar
  - _Klaus
  - _edged
  - _wounding
  - _winds
  - _hol
  - wreck
  keywords:
  - wound
  - wounds
  - winding
  - wounded
  - wen
  - burns
  - trauma
  - heb
  - scar
  - klaus
  - edged
  - wounding
  - winds
  - hol
  - wreck
  - ved
  - hole
  - ended
  - salv
  - botched
- index: 10134
  freq: 0.000327381
  mean_act: 8.6264
  n_distinct: 3
  content_mass: 1.0
  dec_norm: 1.00004
  var_along: 17.2961
  kappa_tilt: 1.98592
  top_tokens:
  - _Part
  - _part
  - Part
  - part
  - _parts
  - _Season
  - _PART
  - PART
  - _Parts
  - _Half
  - parts
  - Parts
  - Act
  - _Act
  - Chapter
  keywords:
  - part
- index: 2851
  freq: 0.000236772
  mean_act: 7.4097
  n_distinct: 4
  content_mass: 1.0
  dec_norm: 1.00004
  var_along: 20.7601
  kappa_tilt: 1.99827
  top_tokens:
  - _expansion
  - _Expansion
  - _expanding
  - _expanded
  - _expand
  - _Panama
  - _expansions
  - _enlarg
  - _DLC
  - _Gateway
  - _contraction
  - olution
  - ement
  - _NASL
  - larg
  keywords:
  - expansion
  - expanding
  - expanded
- index: 24082
  freq: 0.000694444
  mean_act: 4.09666
  n_distinct: 13
  content_mass: 0.928073
  dec_norm: 1.00005
  var_along: 16.3775
  kappa_tilt: 1.55507
  top_tokens:
  - _Attorney
  - _attorney
  - '''s'
  - _prosecutor
  - _General
  - _Sheriff
  - _Justice
  - _attorneys
  - _examiner
  - _Court
  - _District
  - oner
  - _Judge
  - _counsel
  - _Prosecutor
  keywords:
  - attorney
  - prosecutor
  - general
  - sheriff
  - justice
  - attorneys
  - examiner
  - court
  - district
  - oner
  - judge
